#!/usr/bin/env bash
# Decision Ledger v2 — Safety Layer Installer (idempotent)
#
# Installs the pre-commit git hook that routes decision-log/*.md writes through
# the lock + conflict safety layer (concurrent-write guard).
#
# Usage:
#   bash tools/decision-ledger/safety/install.sh [--uninstall]
#
# The hook is installed at .git/hooks/pre-commit in the repository root.
# If a pre-commit hook already exists, the DL hook is appended (not replaced).
#
# Environment:
#   DL_STORE    — decision-log root path (default: auto-detected by hook)
#   DL_ACTOR    — actor initials for git commits (default: git config user.initials)

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
HOOK_DIR="${REPO_ROOT}/.git/hooks"
HOOK_FILE="${HOOK_DIR}/pre-commit"
SAFETY_DIR="$(cd "$(dirname "$0")" && pwd)"
HOOK_MARKER="# DL-SAFETY-HOOK"

uninstall=false
for arg in "$@"; do
  if [[ "$arg" == "--uninstall" ]]; then
    uninstall=true
  fi
done

# -----------------------------------------------------------------------
# Uninstall path
# -----------------------------------------------------------------------
if [[ "$uninstall" == "true" ]]; then
  if [[ -f "$HOOK_FILE" ]]; then
    # Remove the DL hook block (between HOOK_MARKER lines)
    if grep -q "$HOOK_MARKER" "$HOOK_FILE"; then
      # Use python3 for reliable cross-platform multi-line removal
      python3 - "$HOOK_FILE" "$HOOK_MARKER" <<'PYEOF'
import sys, re
hook_file, marker = sys.argv[1], sys.argv[2]
text = open(hook_file).read()
# Remove block from marker to next marker (inclusive)
cleaned = re.sub(
    rf'{re.escape(marker)}.*?{re.escape(marker)}\n?',
    '',
    text,
    flags=re.DOTALL,
)
open(hook_file, 'w').write(cleaned)
print(f"DL safety hook removed from {hook_file}")
PYEOF
    else
      echo "DL safety hook not found in ${HOOK_FILE} — nothing to uninstall."
    fi
  else
    echo "No pre-commit hook at ${HOOK_FILE} — nothing to uninstall."
  fi
  exit 0
fi

# -----------------------------------------------------------------------
# Install path
# -----------------------------------------------------------------------
mkdir -p "$HOOK_DIR"

# Idempotency: if already installed, update the hook block in place
if [[ -f "$HOOK_FILE" ]] && grep -q "$HOOK_MARKER" "$HOOK_FILE"; then
  echo "DL safety hook already installed at ${HOOK_FILE} — updating..."
  python3 - "$HOOK_FILE" "$HOOK_MARKER" "$SAFETY_DIR" <<'PYEOF'
import sys, re
hook_file, marker, safety_dir = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(hook_file).read()
new_block = f"""{marker}
# Auto-generated by tools/decision-ledger/safety/install.sh — do not edit manually.
python3 "{safety_dir}/pre_commit_hook.py" || exit 1
{marker}
"""
cleaned = re.sub(
    rf'{re.escape(marker)}.*?{re.escape(marker)}\n?',
    new_block,
    text,
    flags=re.DOTALL,
)
open(hook_file, 'w').write(cleaned)
print(f"DL safety hook updated in {hook_file}")
PYEOF
  exit 0
fi

# New install — create or append
HOOK_BLOCK="${HOOK_MARKER}
# Auto-generated by tools/decision-ledger/safety/install.sh — do not edit manually.
python3 \"${SAFETY_DIR}/pre_commit_hook.py\" || exit 1
${HOOK_MARKER}"

if [[ ! -f "$HOOK_FILE" ]]; then
  # Create new hook file with shebang
  printf '#!/usr/bin/env bash\nset -euo pipefail\n\n%s\n' "$HOOK_BLOCK" > "$HOOK_FILE"
else
  # Append to existing hook
  printf '\n%s\n' "$HOOK_BLOCK" >> "$HOOK_FILE"
fi

chmod +x "$HOOK_FILE"
echo "DL safety hook installed at ${HOOK_FILE}"
echo ""
echo "The hook will intercept any commit that touches decision-log/*.md files."
echo "It enforces the lock table and conflict safety layer (concurrent-write guard)."
echo ""
echo "To configure actor initials:"
echo "  git config user.initials AR"
echo "Or set DL_ACTOR in your shell environment."
